version: "3"
services:
  client:
    build: ./client
    ports:
      - "8080:8080"
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6-xenial
    ports:
      - "27017:27017"
